/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef student_CONSTANTS_H
#define student_CONSTANTS_H

#include "student_types.h"



class studentConstants {
 public:
  studentConstants();

};

extern const studentConstants g_student_constants;



#endif
